apiVersion: v1
kind: Service
metadata:
  name: app-storage-service
spec:
  selector:
    app: app-storage
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-storage
spec:
  selector:
    matchLabels:
      app: app-storage
  replicas: 2
  template:
    metadata:
      labels:
        app: app-storage
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: aws-secret
      containers:
      - name: app-storage
        image: YOUR_IMAGEM_HERE:latest
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
